% AUTHOR: Jeremy Lilly
% DESCRIPTION: Load data generated by main.m and perform error analysis

close all; clear;

int = [0 1];

exact = load('data/m5j70nkl7l2.mat');

% flatten 2D matrix into 1D 
exact_q = reshape(exact.q_exp', 1, []);
exact_x = reshape(exact.x', 1, []);

% remove repeated cell endpoints
exact_q(100:100:end) = [];
exact_x(100:100:end) = [];

norm_exact = norm(exact_q);

J = [1 2 5 10 20 30 40 50];

errors = zeros(length(J), 5);

for nkl = 1:5
    figure(nkl); hold on;
    for j = 1:length(J)
        
        filename = ['data/m5j', num2str(J(j)), ...
                    'nkl', num2str(nkl), 'l2.mat'];
        approx = load(filename);
        
        % flatten 2D matrix into 1D
        approx_q = reshape(approx.q_exp', 1, []);
        approx_x = reshape(approx.x', 1, []);
        
        % remove repeated cell endpoints
        approx_q(100:100:end-1) = [];
        approx_x(100:100:end-1) = [];
        
        % interpolate approx answer at points where exact soln was
        % evaluated at
        interp_approx = interp1(approx_x, approx_q, exact_x);
        interp_approx(1) = approx_q(1); 
        
        plot(exact_x, interp_approx, ...
             'DisplayName', ['J = ', num2str(J(j))]);
        
        % calculate the l^2 error
        errors(j, nkl) = norm(interp_approx - exact_q) / norm_exact;

    end
    plot(exact_x, exact_q, 'r-.', ...
         'LineWidth', 1.5, 'DisplayName', 'Exact Answer')
    title(['Number of KL Terms = ', num2str(nkl)]);
    axis([0 1 -0.2 1.2])
    legend('Location', 'northwest');
    hold off;
end

figure(6);
surf(errors);

set(gca, 'YTick', 1:length(J));
set(gca, 'YTickLabel', {'1', '2', '5', '10', '20', '30', '40', '50'});
ylabel('Number of Grid Cells');

set(gca, 'XTick', 1:5);
xlabel('Number of KL Terms');

zlabel('Error');
